version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    volumes:
      - .:/var/www/html
    networks:
      - terranusa-network

  db:
    image: mysql:8.0
    container_name: terranusa-db  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: terranusa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - terranusa-network

networks:
  terranusa-network:
    driver: bridge
